/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KjMultiselect {
        "displayProperty": string;
        "options": any[];
        "selectedOptions": any[];
    }
}
declare global {
    interface HTMLKjMultiselectElement extends Components.KjMultiselect, HTMLStencilElement {
    }
    var HTMLKjMultiselectElement: {
        prototype: HTMLKjMultiselectElement;
        new (): HTMLKjMultiselectElement;
    };
    interface HTMLElementTagNameMap {
        "kj-multiselect": HTMLKjMultiselectElement;
    }
}
declare namespace LocalJSX {
    interface KjMultiselect {
        "displayProperty"?: string;
        "onOnselect"?: (event: CustomEvent<any>) => void;
        "options"?: any[];
        "selectedOptions"?: any[];
    }
    interface IntrinsicElements {
        "kj-multiselect": KjMultiselect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kj-multiselect": LocalJSX.KjMultiselect & JSXBase.HTMLAttributes<HTMLKjMultiselectElement>;
        }
    }
}
