/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KjButton {
        "header": string;
    }
    interface KjInputbutton {
        "placeholder": string;
        "value": string;
    }
    interface KjModal {
        "header": string;
        "show": boolean;
    }
    interface KjMultiselect {
        "displayProperty": string;
        "options": any[];
        "selectedOptions": any[];
    }
}
declare global {
    interface HTMLKjButtonElement extends Components.KjButton, HTMLStencilElement {
    }
    var HTMLKjButtonElement: {
        prototype: HTMLKjButtonElement;
        new (): HTMLKjButtonElement;
    };
    interface HTMLKjInputbuttonElement extends Components.KjInputbutton, HTMLStencilElement {
    }
    var HTMLKjInputbuttonElement: {
        prototype: HTMLKjInputbuttonElement;
        new (): HTMLKjInputbuttonElement;
    };
    interface HTMLKjModalElement extends Components.KjModal, HTMLStencilElement {
    }
    var HTMLKjModalElement: {
        prototype: HTMLKjModalElement;
        new (): HTMLKjModalElement;
    };
    interface HTMLKjMultiselectElement extends Components.KjMultiselect, HTMLStencilElement {
    }
    var HTMLKjMultiselectElement: {
        prototype: HTMLKjMultiselectElement;
        new (): HTMLKjMultiselectElement;
    };
    interface HTMLElementTagNameMap {
        "kj-button": HTMLKjButtonElement;
        "kj-inputbutton": HTMLKjInputbuttonElement;
        "kj-modal": HTMLKjModalElement;
        "kj-multiselect": HTMLKjMultiselectElement;
    }
}
declare namespace LocalJSX {
    interface KjButton {
        "header"?: string;
        "onOnclick"?: (event: CustomEvent<any>) => void;
    }
    interface KjInputbutton {
        "onOnsave"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "value"?: string;
    }
    interface KjModal {
        "header"?: string;
        "onOnclose"?: (event: CustomEvent<any>) => void;
        "show"?: boolean;
    }
    interface KjMultiselect {
        "displayProperty"?: string;
        "onOnselect"?: (event: CustomEvent<any>) => void;
        "options"?: any[];
        "selectedOptions"?: any[];
    }
    interface IntrinsicElements {
        "kj-button": KjButton;
        "kj-inputbutton": KjInputbutton;
        "kj-modal": KjModal;
        "kj-multiselect": KjMultiselect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kj-button": LocalJSX.KjButton & JSXBase.HTMLAttributes<HTMLKjButtonElement>;
            "kj-inputbutton": LocalJSX.KjInputbutton & JSXBase.HTMLAttributes<HTMLKjInputbuttonElement>;
            "kj-modal": LocalJSX.KjModal & JSXBase.HTMLAttributes<HTMLKjModalElement>;
            "kj-multiselect": LocalJSX.KjMultiselect & JSXBase.HTMLAttributes<HTMLKjMultiselectElement>;
        }
    }
}
